# Numpy tutorial

**Numpy**
*Numpy*
***Numpy***

#Numpy: provides efficient storage
#fast, uses relatively less memory to store data
#provide better ways to handle data for processing

#Array: 


In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,4])
myarr

array([1, 2, 3, 4])

In [3]:
myarr = np.array([1,2,796853,4], np.int8)
myarr

C:\Users\sosangle\AppData\Local\Temp\ipykernel_13260\3929338650.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 796853 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  myarr = np.array([1,2,796853,4], np.int8)


array([  1,   2, -75,   4], dtype=int8)

In [4]:
myarr[0,1]            #will through error as array is 1D

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [5]:
myarr[1]

2

In [6]:
myarr.shape


(4,)

In [7]:
myarr.dtype


dtype('int8')

In [ ]:
myarr.size


In [ ]:
type(myarr)


In [ ]:
myarr.ndim

In [ ]:
myarr = np.array([[1,2,3,4]])
myarr.shape

In [ ]:
myarr[0,1]

In [ ]:
myarr[0,1]=9
myarr

# Array creation using other objects

In [ ]:
listarray = np.array([[1,2,3], [4,5,6],[7,8,9]])
listarray

# intrinsic numpy array creation objects(arange, ones, zeros, etc)

In [ ]:
# np by zeros: it will give the array of size (2,5) with value 0 for all positions
zeros = np.zeros((2,5))
zeros

In [ ]:
# np by arange(a-range): it will give the array of 0-14 values
rng = np.arange(15)
rng

In [ ]:
# np by ones: it will give the array of size (2,5) with value 1 for all positions
one = np.ones((2,5))     #or np.ones((2)) 
one

In [ ]:
# Linspace: it will give 1-20 linearlly/equally spaced 12 elements
lspace = np.linspace(1, 20, 12)
lspace

In [ ]:
lspace = np.linspace(1, 20, 20)
lspace

In [ ]:
#it will give the empty array with random elemets and we can ressign those elemts
emp = np.empty((4, 6))   
emp

In [ ]:
#it will give the empty array,elemets like passed array and we can ressign those elemts
emp = np.empty_like(lspace)   
emp

In [ ]:
# will give the identity array or metrics
ide = np.identity(5)
ide

In [ ]:
arr = np.arange(99)
arr

In [ ]:
# will reshape 1d array to nD array
arr = arr.reshape(3, 33)
arr

In [ ]:
# will reshape nd array to 1D array
arr = arr.ravel()
arr

# Axis:
**1d array: no of axis 1 i.e., 0**

**2d array: no of axis 2 i.e., 0(all columns),1(all rows)**
    
    e.g.,
    [[1,2,3],[4,5,6],[7,8,9]]
    sum_of_axis0 = [1+4+7, 2+5+8, 3+6+9] = [12, 15, 18]
    sum_of_axis1 = [1+2+3, 4+5+6, 7+8+9] = [ 6, 15, 24]

In [23]:
x = [[1,2,3],[4,0,6], [7,8,5]]
arr = np.array(x)
arr


array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 5]])

In [24]:
arr.sum(axis=0)

array([12, 10, 14])

In [25]:
arr.sum(axis=1)

array([ 6, 10, 20])

In [26]:
#Transpose of array
arr.T

array([[1, 4, 7],
       [2, 0, 8],
       [3, 6, 5]])

In [27]:
# will flatten the array
for item in arr.flat:
    print(item)

1
2
3
4
0
6
7
8
5


In [13]:
# total bytes consumed
arr.nbytes

36

In [17]:
# gives index of max element
one = np.array([1,2,34,66, 4, 3])
one.argmax()

3

In [15]:
one.argmin()

0

In [18]:
# gives the array of index sequence which will sort array
one.argsort()

array([0, 1, 5, 4, 2, 3], dtype=int64)

In [28]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 5]])

In [35]:
# 1st it will flatten the array then search for min element and prints the index of that element
arr.argmin(),    arr.argmax()

(4, 7)

In [30]:
arr.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [31]:
arr.argmax(axis = 0), '\n', arr.argmax(axis = 1)

(array([2, 2, 1], dtype=int64), '\n', array([2, 2, 1], dtype=int64))

In [36]:
arr.argsort(axis=0)

array([[0, 1, 0],
       [1, 0, 2],
       [2, 2, 1]], dtype=int64)

In [37]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [39]:
arr.ravel()

array([1, 2, 3, 4, 0, 6, 7, 8, 5])

In [40]:
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 5]])

In [43]:
arr2 = np.array([[4,2,3],[4,0,1], [6,1,5]])
arr2


array([[4, 2, 3],
       [4, 0, 1],
       [6, 1, 5]])

In [44]:
arr + arr2

array([[ 5,  4,  6],
       [ 8,  0,  7],
       [13,  9, 10]])

# +
if we use + for arr, it will add elements of two array but on list it will extend the list

In [45]:
arr * arr2

array([[ 4,  4,  9],
       [16,  0,  6],
       [42,  8, 25]])

In [47]:
arr - arr2

array([[-3,  0,  0],
       [ 0,  0,  5],
       [ 1,  7,  0]])

In [49]:
arr2 / arr

C:\Users\sosangle\AppData\Local\Temp\ipykernel_13260\2501189345.py:1: RuntimeWarning: invalid value encountered in divide
  arr2 / arr


array([[4.        , 1.        , 1.        ],
       [1.        ,        nan, 0.16666667],
       [0.85714286, 0.125     , 1.        ]])

In [52]:
np.sqrt(arr2)

array([[2.        , 1.41421356, 1.73205081],
       [2.        , 0.        , 1.        ],
       [2.44948974, 1.        , 2.23606798]])

In [54]:
# argmax or argmin will give the index of max or min element, but max & min will give the value of element
arr.sum(), arr.max(), arr.min()

(36, 8, 0)

In [56]:
# to find the element: gives tuple of array of position index
# o/p: [1, 2, 2], [2, 0, 1] => element at(1,2), (2,0),(2,1)
np.where(arr>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [57]:
np.count_nonzero(arr)

8

In [58]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [59]:
import sys

In [60]:
py_array = [0, 4, 55, 2]
np_array = np.array(py_array)

In [68]:
sys.getsizeof(1) * len(py_array)

4

In [70]:
np_array.itemsize * np_array.size

4

In [67]:
sys.getsizeof(1)

28